name: Deploy to AWS

# Se ejecutará solo cuando hagas push a la rama 'test'
on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir y subir imagen a Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projectawsrestaurant-readcustomer:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/projectawsrestaurant-readcustomer:latest

      - name: Conectar a AWS EC2 y desplegar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Verificar si el puerto 5000 está en uso y liberarlo si es necesario
            if sudo lsof -i:5000; then
              echo "Puerto 5000 en uso. Liberando..."
              sudo fuser -k 5000/tcp
            fi

            # Detener y eliminar el contenedor si existe
            sudo docker stop readcustomer || true
            sudo docker rm readcustomer || true

            # Descargar la última imagen desde Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/projectawsrestaurant-readcustomer:latest

            # Ejecutar el contenedor en el puerto 5000
            sudo docker run -d -p 5000:5000 --name readcustomer ${{ secrets.DOCKER_USERNAME }}/projectawsrestaurant-readcustomer:latest
